// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2clA43AB1gIPYdQdvkPHOjCdurS98380',
    appId: '1:679488034391:web:75c5cace4ffd2148d5f512',
    messagingSenderId: '679488034391',
    projectId: 'apptaxi-89d1b',
    authDomain: 'apptaxi-89d1b.firebaseapp.com',
    databaseURL: 'https://apptaxi-89d1b-default-rtdb.firebaseio.com',
    storageBucket: 'apptaxi-89d1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTFeEQz-RdpsZelQQD_15ep9Pn-hyMdLk',
    appId: '1:679488034391:android:21f0395d33c1a56dd5f512',
    messagingSenderId: '679488034391',
    projectId: 'apptaxi-89d1b',
    databaseURL: 'https://apptaxi-89d1b-default-rtdb.firebaseio.com',
    storageBucket: 'apptaxi-89d1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq0qdQejsgne_f24gxqswfxoo6HE_QcTE',
    appId: '1:679488034391:ios:a7303e0f883258e9d5f512',
    messagingSenderId: '679488034391',
    projectId: 'apptaxi-89d1b',
    databaseURL: 'https://apptaxi-89d1b-default-rtdb.firebaseio.com',
    storageBucket: 'apptaxi-89d1b.appspot.com',
    iosClientId: '679488034391-qtp9o1o9teu1e6lb42ad97qitupio2vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq0qdQejsgne_f24gxqswfxoo6HE_QcTE',
    appId: '1:679488034391:ios:a7303e0f883258e9d5f512',
    messagingSenderId: '679488034391',
    projectId: 'apptaxi-89d1b',
    databaseURL: 'https://apptaxi-89d1b-default-rtdb.firebaseio.com',
    storageBucket: 'apptaxi-89d1b.appspot.com',
    iosClientId: '679488034391-qtp9o1o9teu1e6lb42ad97qitupio2vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2clA43AB1gIPYdQdvkPHOjCdurS98380',
    appId: '1:679488034391:web:578f56926cce9e3bd5f512',
    messagingSenderId: '679488034391',
    projectId: 'apptaxi-89d1b',
    authDomain: 'apptaxi-89d1b.firebaseapp.com',
    databaseURL: 'https://apptaxi-89d1b-default-rtdb.firebaseio.com',
    storageBucket: 'apptaxi-89d1b.appspot.com',
  );

}